version: "3.8"

services:
  db:
    container_name: pgcontainer
    image: postgres:14-alpine
    restart: always
    environment:
      # - POSTGRES_USER=postgres
      # - POSTGRES_PASSWORD=postgres
      # - POSTGRES_DB=postgres
      POSTGRES_USER: ${DOCKER_USER}
      POSTGRES_PASSWORD: ${DOCKER_PASS}
      POSTGRES_DB: ${DOCKER_DB}

    ports:
      - '5432:5432'
    volumes:
      - ./postgres-data:/var/lib/postgresql/data

  app:
      restart: on-failure
      build: .
      depends_on:
        - db
      environment:
        DABASE_URL: postgresql://${DOCKER_USER}:${DOCKER_PASS}@db:5432/${DOCKER_DB}
        NODE_ENV: development
        PORT: 3000
      ports:
        - '3000:3000'
      command: yarn start
      volumes:
       - .:/app
       - /app/node_modules
